"""
P1 #10 — generate ``.env.example`` from the Settings model.

Walks ``Settings.model_fields`` and emits a section per field with its
name, type, default value, and the docstring captured in
``Field(description=...)`` or the inline triple-quoted docstring line
that follows the field.

Run via:

    python -m backend.config.gen_env > .env.example

CI drift guard (pre-commit + GitHub Action):

    python -m backend.config.gen_env > /tmp/env.example.new
    diff -u .env.example /tmp/env.example.new

The CI step fails if a contributor adds a Settings field without
regenerating .env.example, so the docs can't drift behind the code.

Why generate vs. write by hand: 47 settings fields, only 31 in the
hand-rolled .env.example. ~16 settings undocumented to operators. A
real adoption blocker once we ship to anyone outside the team.
"""
from __future__ import annotations

import os
import sys
from typing import Any, Iterable, get_args

# Allow gen_env to run without a real JWT secret etc — we're just inspecting
# the model, not instantiating it for runtime. A non-empty placeholder
# secret avoids the dev-mode ephemeral-secret WARN log that would
# otherwise pollute stdout (and produce false drift in env-example-check
# on every run, since the WARN includes a fresh timestamp).
os.environ.setdefault("JWT_SECRET_KEY", "gen-env-placeholder-not-a-real-secret-32-chars")
os.environ.setdefault("ENVIRONMENT", "development")

# structlog defaults to stdout; redirect to stderr while we import settings
# so any WARN log emitted during construction doesn't leak into the
# generated .env.example. We only need this during import.
import contextlib
with contextlib.redirect_stdout(sys.stderr):
    from backend.config.settings import Settings


def _format_default(default: Any) -> str:
    """Render a default value in env-string form."""
    if default is None or default == "":
        return ""
    if isinstance(default, bool):
        return "true" if default else "false"
    if isinstance(default, (list, tuple)):
        # Settings uses CSV strings for list-shaped envs (cors_origins etc).
        # If we ever hit a real list field we'd render comma-separated;
        # currently no Settings field is typed list, so this is defensive.
        return ",".join(str(x) for x in default)
    return str(default)


def _format_type(annotation: Any) -> str:
    """Render the field's type in a way ops can read."""
    if annotation is None:
        return "any"
    # Strip Optional/Union noise.
    args = get_args(annotation)
    if args:
        non_none = [a for a in args if a is not type(None)]
        if len(non_none) == 1:
            annotation = non_none[0]
    name = getattr(annotation, "__name__", str(annotation))
    return name


def render_env_example() -> str:
    lines: list[str] = []
    lines.append("# .env.example — kemory configuration reference.")
    lines.append("# AUTO-GENERATED by `python -m backend.config.gen_env`. Do not edit by hand.")
    lines.append("# CI fails the build if this file drifts from the Settings model.")
    lines.append("#")
    lines.append("# Fields are listed in source order. For each field:")
    lines.append("#   <ENV_VAR_NAME>=<default>   # <type>; <description if present>")
    lines.append("")

    for field_name, info in Settings.model_fields.items():
        env_name = field_name.upper()
        default = _format_default(info.default)
        type_name = _format_type(info.annotation)
        description = (info.description or "").strip()

        comment_parts: list[str] = [type_name]
        if description:
            comment_parts.append(description)
        comment = "; ".join(comment_parts)

        lines.append(f"# {comment}")
        lines.append(f"{env_name}={default}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main(argv: Iterable[str] | None = None) -> int:
    sys.stdout.write(render_env_example())
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main(sys.argv[1:]))
