/**
 * Keycloak SSO service for the Memory Vault dashboard.
 *
 * Singleton pattern — initialises once with PKCE S256 and check-sso.
 * Persists tokens in sessionStorage to survive page refreshes.
 *
 * Configuration is loaded at runtime from /config.json (generated by
 * docker-entrypoint.sh) so the same Docker image works across environments.
 * Falls back to VITE_ env vars for local dev.
 */
import Keycloak from 'keycloak-js'

interface RuntimeConfig {
  KEYCLOAK_URL: string
  KEYCLOAK_REALM: string
  KEYCLOAK_CLIENT_ID: string
  SKIP_AUTH: string
  API_KEY?: string
  API_URL?: string
}

let _config: RuntimeConfig | null = null

export async function loadConfig(): Promise<RuntimeConfig> {
  if (_config) return _config
  try {
    const resp = await fetch('/config.json')
    if (resp.ok) {
      _config = await resp.json()
    }
  } catch {
    // Fallback below
  }
  if (!_config) {
    _config = {
      KEYCLOAK_URL: import.meta.env.VITE_KEYCLOAK_URL ?? '/auth',
      KEYCLOAK_REALM: import.meta.env.VITE_KEYCLOAK_REALM ?? 's9n-mvp',
      KEYCLOAK_CLIENT_ID: import.meta.env.VITE_KEYCLOAK_CLIENT_ID ?? 'kemory-dashboard',
      SKIP_AUTH: import.meta.env.VITE_SKIP_AUTH ?? 'false',
    }
  }
  return _config!
}

export function getConfig(): RuntimeConfig | null {
  return _config
}

let keycloak: Keycloak | null = null
let initPromise: Promise<boolean> | null = null

function createKeycloak(config: RuntimeConfig): Keycloak {
  if (!keycloak) {
    keycloak = new Keycloak({
      url: config.KEYCLOAK_URL,
      realm: config.KEYCLOAK_REALM,
      clientId: config.KEYCLOAK_CLIENT_ID,
    })
  }
  return keycloak
}

export function getKeycloak(): Keycloak {
  if (!keycloak) {
    throw new Error('Keycloak not initialised — call initKeycloak() first')
  }
  return keycloak
}

export async function initKeycloak(): Promise<boolean> {
  if (initPromise) return initPromise

  const config = await loadConfig()
  if (config.SKIP_AUTH === 'true') return false

  const kc = createKeycloak(config)

  const kcInit = kc.init({
    onLoad: 'check-sso',
    pkceMethod: 'S256',
    silentCheckSsoRedirectUri: `${window.location.origin}/silent-check-sso.html`,
    checkLoginIframe: false,
    token: sessionStorage.getItem('kc_token') ?? undefined,
    refreshToken: sessionStorage.getItem('kc_refreshToken') ?? undefined,
  })

  // Timeout after 10s to prevent hanging if silent SSO check fails
  const timeout = new Promise<boolean>((_, reject) =>
    setTimeout(() => reject(new Error('Keycloak init timed out')), 10_000),
  )

  initPromise = Promise.race([kcInit, timeout])

  const authenticated = await initPromise

  if (authenticated) {
    persistTokens(kc)
    startTokenRefresh(kc)
  }

  return authenticated
}

function persistTokens(kc: Keycloak) {
  if (kc.token) sessionStorage.setItem('kc_token', kc.token)
  if (kc.refreshToken) sessionStorage.setItem('kc_refreshToken', kc.refreshToken)
}

function clearTokens() {
  sessionStorage.removeItem('kc_token')
  sessionStorage.removeItem('kc_refreshToken')
}

let refreshInterval: ReturnType<typeof setInterval> | null = null

function startTokenRefresh(kc: Keycloak) {
  if (refreshInterval) clearInterval(refreshInterval)
  refreshInterval = setInterval(async () => {
    try {
      const refreshed = await kc.updateToken(30)
      if (refreshed) persistTokens(kc)
    } catch {
      clearTokens()
      kc.login()
    }
  }, 60_000)
}

export function login(redirectUri?: string) {
  clearTokens()
  getKeycloak().login({ redirectUri: redirectUri ?? window.location.href })
}

export function logout() {
  clearTokens()
  getKeycloak().logout({ redirectUri: window.location.origin + '/login' })
}

export function getToken(): string | undefined {
  return getKeycloak().token
}

export function getUserRoles(): string[] {
  return getKeycloak().realmAccess?.roles ?? []
}

export function hasRole(role: string): boolean {
  return getUserRoles().includes(role)
}

export interface KeycloakUser {
  id: string
  username: string
  email: string
  firstName: string
  lastName: string
  roles: string[]
}

export function getUser(): KeycloakUser | null {
  const kc = getKeycloak()
  if (!kc.authenticated || !kc.tokenParsed) return null

  return {
    id: kc.tokenParsed.sub ?? '',
    username: kc.tokenParsed.preferred_username ?? '',
    email: kc.tokenParsed.email ?? '',
    firstName: kc.tokenParsed.given_name ?? '',
    lastName: kc.tokenParsed.family_name ?? '',
    roles: getUserRoles(),
  }
}
